### ISSUE TITLE
Support enumerations

### ISSUE THREAD

**Issue by ksaifullah** [mscharley/generic-type-guard#47]

**Comment by mscharley** [comment]
According to the docs this should be pretty trivial to do via a reverse lookup for integer enumerations.

From the docs: 
> Keep in mind that string enum members do not get a reverse mapping generated at all.

Not sure the best way to handle string enumerations.

**Comment by mscharley** [comment]
From a technical perspective, string enumerations could be handled as a `isSingletonStringUnion()` that returned `o is MyEnumeration` instead of the string union type. This isn't guaranteed typesafe though because you could get both false positives and false negatives since there's no way to enforce that the strings provided are part of the enumeration and there's no way to interrogate the string union for the valid options.

This may need to way to for the codegen options in the CLI to be feasible to support well.

To be honest, a string union is usually more flexible and useful. But sometimes the extra inflexibility of an enum is what you need too.

**Comment by mscharley** [comment]
The following approach works with `const enum`s and can not generate false positives. It can still generate false negatives if you do not list all values exhaustively, but that's a known issue in general at the moment and acceptable.

```
enum BooleanEnum {
    No = "NO",
    Yes = "YES",
}

const isStringEnum = <T>(...vs: T[]) => (v: any): v is T =>
    vs.indexOf(v) >= 0;

const isBooleanEnum =
    isStringEnum<BooleanEnum>(BooleanEnum.Yes, BooleanEnum.No);

let foo = "YES";
let bar: BooleanEnum;

if (isBooleanEnum(foo)) {
    bar = foo;
}
```

**Comment by mscharley** [comment]
`isStringEnum` above is really `isConstEnum` - it works equally well for string enums, const or otherwise, and also for numeric cost enums.

We can do one better for numeric enums though:

```typescript
enum Flags {
    Read = 4,
    Write = 2,
    Execute = 1,
}

const isNumericEnum = <T extends { [n: number]: string }>(vs: T) =>
    (v: any): v is T => typeof v === "number" && v in vs;

const isFlag = isNumericEnum(Flags);

let foo = 1;
let bar: Flags;

if (isFlag(foo)) {
    bar = foo;
}
```
